### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jardevil** [MarcelJurtz/Ich-hab-noch-nie#1]
Moin!

Could you consider adding a copyleft license, I would like to integrate your data into my repo, but can't do that legally :/

[never-have-i-ever_german.yaml.txt](https://github.com/MarcelJurtz/Ich-hab-noch-nie/files/2431090/never-have-i-ever_german.yaml.txt)

**Comment by MarcelJurtz** [comment]
Done :) Feel free to add your content, unfortunately, i don't have the time at the moment to actively take care of this project. Thanks for the contribution!
